name: tubes_nguliks
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.0
  firebase_storage: ^12.4.3
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
